---
swagger: "2.0"
info:
  description: This is a simple API
  version: 1.0.0
  title: MakerMap IQP API
  contact:
    email: gr-makermap@wpi.edu
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: virtserver.swaggerhub.com
basePath: /MakerMap/makermap_api/1.0.0
tags:
- name: admin
  description: Secured Admin-only calls
- name: user
  description: Operations available to regular users
schemes:
- https
paths:
  /searchMap:
    get:
      tags:
      - user
      - admin
      summary: get list of buildings
      description: |
        get list of buildings
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: searchMapRequest
        description: get list of buildings
        required: false
        schema:
          $ref: '#/definitions/searchMapRequest'
      responses:
        "200":
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/Building'
        "400":
          description: bad input parameter
  /addBuilding:
    post:
      tags:
      - admin
      summary: add a building to the map
      description: |
        input new building into map
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: addBuildingRequest
        description: add building to map
        required: false
        schema:
          $ref: '#/definitions/addBuildingRequest'
      responses:
        "200":
          description: building added
          schema:
            type: array
            items:
              $ref: '#/definitions/Building'
        "400":
          description: bad input parameter
  /addLab:
    post:
      tags:
      - admin
      summary: add a lab to the map
      description: |
        input a new building into map
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: addLabRequest
        description: add lab to map
        required: false
        schema:
          $ref: '#/definitions/addLabRequest'
      responses:
        "200":
          description: lab added
          schema:
            type: array
            items:
              $ref: '#/definitions/Lab'
        "400":
          description: bad input parameter
  /addTool:
    post:
      tags:
      - admin
      summary: add a tool to the map
      description: |
        input new tool into map
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: addToolRequest
        description: add tool to map
        required: false
        schema:
          $ref: '#/definitions/addToolRequest'
      responses:
        "200":
          description: tool added
          schema:
            type: array
            items:
              $ref: '#/definitions/Tool'
        "400":
          description: bad input parameter
  /addTag:
    post:
      tags:
      - admin
      summary: add a tag to the map
      description: |
        input new tag into map
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: addTagRequest
        description: add tag to map
        required: false
        schema:
          $ref: '#/definitions/addTagRequest'
      responses:
        "200":
          description: tag added
          schema:
            type: array
            items:
              $ref: '#/definitions/Tag'
        "400":
          description: bad input parameter
definitions:
  Building:
    type: object
    required:
    - address
    - description
    - hours
    - image
    - lat
    - long
    - manager
    - name
    properties:
      name:
        type: string
      address:
        type: string
      lat:
        type: number
      long:
        type: number
      description:
        type: string
      image:
        type: string
        format: url
      manager:
        type: string
        format: uuid
      hours:
        type: string
  Lab:
    type: object
    required:
    - Building
    - description
    - hours
    - lat
    - long
    - manager
    - name
    properties:
      Building:
        type: object
        properties: {}
      name:
        type: string
      lat:
        type: number
      long:
        type: number
      description:
        type: string
      image:
        type: string
        format: url
      manager:
        type: string
        format: uuid
      hours:
        type: string
  Tool:
    type: object
    required:
    - Lab
    - bookingLink
    - description
    - images
    - name
    - owner
    - restrictPublic
    properties:
      Lab:
        type: object
        properties: {}
      name:
        type: string
      description:
        type: string
      images:
        type: string
        format: url
      owner:
        type: string
        format: uuid
      bookingLink:
        type: string
        format: url
      restrictPublic:
        type: boolean
        default: false
  Person:
    type: object
    required:
    - description
    - email
    - image
    - name
    - officeLocation
    - phone
    - title
    properties:
      name:
        type: string
      description:
        type: string
      image:
        type: string
        format: url
      email:
        type: string
      officeLocation:
        type: string
      phone:
        type: string
      title:
        type: string
  Event:
    type: object
    required:
    - description
    - endTime
    - image
    - link
    - name
    - person
    - startTime
    properties:
      name:
        type: string
      description:
        type: string
      image:
        type: string
        format: url
      link:
        type: string
        format: url
      startTime:
        type: integer
      endTime:
        type: integer
      person:
        type: string
  Tag:
    type: object
    required:
    - name
    - obj_uuid
    - table
    properties:
      name:
        type: string
      table:
        type: string
      obj_uuid:
        type: string
        format: uuid
  searchMapRequest:
    type: object
    required:
    - uuid
    properties:
      searchTerm:
        type: string
      uuid:
        type: string
        format: uuid
  addBuildingRequest:
    type: object
    required:
    - address
    - description
    - hours
    - image
    - lat
    - long
    - manager
    - name
    properties:
      name:
        type: string
      address:
        type: string
      lat:
        type: number
      long:
        type: number
      description:
        type: string
      image:
        type: string
        format: url
      manager:
        type: string
        format: uuid
      hours:
        type: string
  addLabRequest:
    type: object
    required:
    - Building
    - description
    - hours
    - lat
    - long
    - manager
    - name
    properties:
      Building:
        type: object
        properties: {}
      name:
        type: string
      lat:
        type: number
      long:
        type: number
      description:
        type: string
      image:
        type: string
        format: url
      manager:
        type: string
        format: uuid
      hours:
        type: string
  addToolRequest:
    type: object
    required:
    - Lab
    - bookingLink
    - description
    - images
    - name
    - owner
    - restrictPublic
    properties:
      Lab:
        type: object
        properties: {}
      name:
        type: string
      description:
        type: string
      images:
        type: string
        format: url
      owner:
        type: string
        format: uuid
      bookingLink:
        type: string
        format: url
      restrictPublic:
        type: boolean
        default: false
  addTagRequest:
    type: object
    required:
    - name
    - obj_uuid
    - table
    properties:
      name:
        type: string
      table:
        type: string
      obj_uuid:
        type: string
        format: uuid
